(ns pl.tomaszgigiel.xml-to-csv.merging-test
  (:use [clojure.test])
  (:require [clojure.edn :as edn])
  (:require [clojure.java.io :as io])
  (:require [clojure.xml :as clojure-xml])
  (:require [pl.tomaszgigiel.xml-to-csv.merging :as merging])
  (:require [pl.tomaszgigiel.xml-to-csv.misc :as misc])
  (:require [pl.tomaszgigiel.xml-to-csv.test-config :as test-config]))

(use-fixtures :once test-config/once-fixture)
(use-fixtures :each test-config/each-fixture)

(let [a (->> "a/input.xml" io/resource str clojure-xml/parse)
      b (->> "b/input.xml" io/resource str clojure-xml/parse)
      c (->> "c/input.xml" io/resource str clojure-xml/parse)
      d (->> "d/input.xml" io/resource str clojure-xml/parse)
      e (->> "e/input.xml" io/resource str clojure-xml/parse)
      f (->> "f/input.xml" io/resource str clojure-xml/parse)
      g (->> "g/input.xml" io/resource str clojure-xml/parse)
      h (->> "h/input.xml" io/resource str clojure-xml/parse)
      i (->> "i/input.xml" io/resource str clojure-xml/parse)
      j (->> "j/input.xml" io/resource str clojure-xml/parse)
      k (->> "k/input.xml" io/resource str clojure-xml/parse)
      l (->> "l/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)]

  (deftest merged-test
    ;;(is (= (->> "a/merged.edn" misc/string-from-resource edn/read-string) (merging/merged a)))
    ;;(is (= (->> "b/merged.edn" misc/string-from-resource edn/read-string) (merging/merged b)))
    ;;(is (= (->> "c/merged.edn" misc/string-from-resource edn/read-string) (merging/merged c)))
    ;;(is (= (->> "d/merged.edn" misc/string-from-resource edn/read-string) (merging/merged d)))
    ;;(is (= (->> "e/merged.edn" misc/string-from-resource edn/read-string) (merging/merged e)))
    ;;(is (= (->> "f/merged.edn" misc/string-from-resource edn/read-string) (merging/merged f)))
    ;;(is (= (->> "g/merged.edn" misc/string-from-resource edn/read-string) (merging/merged g)))
    ;;(is (= (->> "h/merged.edn" misc/string-from-resource edn/read-string) (merging/merged h)))
    ;;(is (= (->> "i/merged.edn" misc/string-from-resource edn/read-string) (merging/merged i)))
    ;;(is (= (->> "j/merged.edn" misc/string-from-resource edn/read-string) (merging/merged j)))
    ;;(is (= (->> "k/merged.edn" misc/string-from-resource edn/read-string) (merging/merged k)))
    (is (= (->> "l/merged.edn" misc/string-from-resource edn/read-string) (merging/merged l)))
   )
)