(ns pl.tomaszgigiel.xml-to-csv.merging-test
  (:use [clojure.test])
  (:require [clojure.edn :as edn])
  (:require [clojure.java.io :as io])
  (:require [clojure.xml :as clojure-xml])
  (:require [pl.tomaszgigiel.xml-to-csv.merging :as merging])
  (:require [pl.tomaszgigiel.xml-to-csv.misc :as misc])
  (:require [pl.tomaszgigiel.xml-to-csv.test-config :as test-config]))

(use-fixtures :once test-config/once-fixture)
(use-fixtures :each test-config/each-fixture)

(let [a (->> "a/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      b (->> "b/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      c (->> "c/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      d (->> "d/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      e (->> "e/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      f (->> "f/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      g (->> "g/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      h (->> "h/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      i (->> "i/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      j (->> "j/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      k (->> "k/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)
      l (->> "l/tree-to-rows-helper.edn" misc/string-from-resource edn/read-string)]

  (deftest merged-test
    (is (= (->> "a/merged.edn" misc/string-from-resource edn/read-string) (merging/merged a)))
    (is (= (->> "b/merged.edn" misc/string-from-resource edn/read-string) (merging/merged b)))
    (is (= (->> "c/merged.edn" misc/string-from-resource edn/read-string) (merging/merged c)))
    (is (= (->> "d/merged.edn" misc/string-from-resource edn/read-string) (merging/merged d)))
    (is (= (->> "e/merged.edn" misc/string-from-resource edn/read-string) (merging/merged e)))
    (is (= (->> "f/merged.edn" misc/string-from-resource edn/read-string) (merging/merged f)))
    (is (= (->> "g/merged.edn" misc/string-from-resource edn/read-string) (merging/merged g)))
    (is (= (->> "h/merged.edn" misc/string-from-resource edn/read-string) (merging/merged h)))
    (is (= (->> "i/merged.edn" misc/string-from-resource edn/read-string) (merging/merged i)))
    (is (= (->> "j/merged.edn" misc/string-from-resource edn/read-string) (merging/merged j)))
    (is (= (->> "k/merged.edn" misc/string-from-resource edn/read-string) (merging/merged k)))
    (is (= (->> "l/merged.edn" misc/string-from-resource edn/read-string) (merging/merged l)))
   )
)