(ns pl.tomaszgigiel.xml-to-csv.temp-test
  (:use [clojure.set])
  (:use [clojure.test])
  (:require [clojure.data.xml :as data-xml])
  (:require [clojure.edn :as edn])
  (:require [clojure.java.io :as io])
  (:require [clojure.string :as string])
  (:require [clojure.xml :as clojure-xml])
  (:require [pl.tomaszgigiel.xml-to-csv.common :as common])
  (:require [pl.tomaszgigiel.xml-to-csv.misc :as misc])
  (:require [pl.tomaszgigiel.xml-to-csv.test-config :as test-config])
  (:import java.io.StringReader))

(def a9p (->> "a09/input.xml" io/resource str clojure-xml/parse))
(def a9 (-> "a09/input.xml" io/resource str clojure-xml/parse (common/tree-to-rows-helper "")))
